apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-acg
  region: us-east-1
  version: "1.25"

vpc:
  cidr: 10.0.0.0/16
  nat:
    gateway: HighlyAvailable
nodeGroups:
  - name: eks-node-group
    instanceType: t3.medium
    desiredCapacity: 3
    privateNetworking: true
    volumeSize: 30

availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"] # This is required since in us-east-1 only 2 subnets are created by default (https://eksctl.io/usage/vpc-networking/)
